# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa222c565eeb6a17168babc9305bf927c5a864eed3f9aec6f1422782f42c807b29728b4980207392ed9516b3954d544046152c3dd710c57ac1e4a3a9c80b6d37

test:
  secret_key_base: 2c8d865660434427bfb6cbcb764932c8960155e2e21b2cddf84c67b38758ffc64d1a770b988dba91d2a889bb83f8d068a2ee5bd66f3af1b99397417ca36b43e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
